apiVersion: v1
kind: Service
metadata:
  name: transaction
  namespace: ibm-bank
  labels:
    app: transaction
    service: transaction
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: transaction
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-app
  namespace: ibm-bank
  labels:
    app: transaction
    version: v1
spec:
  selector:
    matchLabels:
      app: transaction
  replicas: 1
  template:
    metadata:
      labels:
        app: transaction
        version: v1
    spec:
      containers:
        - name: transaction
          image: docker.io/src32/ibm-bank-transaction:v0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: tonyfieit75-pull-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  namespace: ibm-bank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ibm-bank.detera.local
      http:
        paths:
          - path: /transaction
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  number: 8080
